# ==========================================
# Picom Config - Essencialista
# ==========================================

# --- Motor Gráfico (O Segredo do Blur) ---
backend = "glx";
vsync = true;
use-damage = true;

# --- Cantos Arredondados ---
corner-radius = 12;
detect-rounded-corners = true;

# --- Desfoque (Blur) ---
blur-method = "dual_kawase";
blur-strength = 6;
blur-background = true;

# --- Sombras ---
shadow = true;
shadow-radius = 15;
shadow-opacity = 0.4;
shadow-offset-x = -15;
shadow-offset-y = -15;

# --- Animações (Fading) ---
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

# --- Regras de Exceção ---
rules = (
  # Remove sombras de menus e tooltips
  {
    match = "window_type = 'tooltip' || window_type = 'menu' || window_type = 'dropdown_menu' || window_type = 'popup_menu'";
    shadow = false;
  },
  # Remove blur e cantos da barra do i3 e do papel de parede
  {
    match = "window_type = 'dock' || window_type = 'desktop' || _GTK_FRAME_EXTENTS@";
    blur-background = false;
    corner-radius = 0;
  }
  # Impede que o Picom interfira na ferramenta de seleção de print (slop)
  {
    match = "class_g = 'slop'";
    blur-background = false;
    shadow = false;
    fade = false;
    opacity = 1.0;
  },
);

