conky.config = {
    alignment = 'top_right',
    background = true,
    use_xft = true,
    font = 'Monospace:size=11:bold',
    gap_x = 40,
    gap_y = 60,
    update_interval = 86400,
    double_buffer = true,
    own_window = true,
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    default_color = '#FFFFFF',
    draw_shades = true,
}

conky.text = [[
${color {PRIMARYCOLOR}}=== GUIA RÁPIDO DE ATALHOS ===${color}
${color {SECUNDARYCOLOR}}Terminal:${color}        $mod + Return  ou  $mod + x
${color {SECUNDARYCOLOR}}Navegador:${color}       $mod + n (Chrome)  ou  $mod + b (Brave)
${color {SECUNDARYCOLOR}}Fechar Janela:${color}   $mod + Shift + q
${color {SECUNDARYCOLOR}}Mudar Workspace:${color} $mod + 1 ... 9
${color {SECUNDARYCOLOR}}Mover Janela:${color}    $mod + Shift + 1 ... 9
${color {SECUNDARYCOLOR}}Encerrar Sessão:${color} $mod + Shift + e
]]