conky.config = {
    alignment = 'bottom_left',
    background = true,
    use_xft = true,
    font = 'Hack Nerd Font:size=11:bold',
    gap_x = 40,
    gap_y = 60,
    update_interval = 86400,
    double_buffer = true,
    own_window = true,
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    default_color = '#FFFFFF',
    draw_shades = true,
}

conky.text = [[
${color {PRIMARYCOLOR}}=== GUIA RÁPIDO DE ATALHOS ===${color}
${color {SECUNDARYCOLOR}}Terminal:${color}         + Enter  ${color {SECUNDARYCOLOR}}ou${color}   + x
${color {SECUNDARYCOLOR}}Navegador:${color}        + n (Chrome)  ${color {SECUNDARYCOLOR}}ou${color}   + b (Brave)
${color {SECUNDARYCOLOR}}Fechar Janela:${color}    + Shift + q
${color {SECUNDARYCOLOR}}Mudar Workspace:${color}  + 1 ${color {SECUNDARYCOLOR}}...${color} 9
${color {SECUNDARYCOLOR}}Mover Janela:${color}     + Shift + 1 ${color {SECUNDARYCOLOR}}...${color} 9
${color {SECUNDARYCOLOR}}Encerrar Sessão:${color}  + Shift + e
]]